### ISSUE TITLE
Is this repo active?

### ISSUE THREAD

**Issue by TheTedAdams** [kmees/react-fabric#2]
Hello @kmees ,

Really like the start here, but nervous to take a dependency with no work in 5 months. If I start using this repo I would be PRing back to it. Are you still actively interested in this project? Would you be interested in adding owners or handing over the project if you are no longer actively interested?

Just curious where this stands before I consider taking this repo as a dependency.

**Comment by kmees** [comment]
No its not. There were some gamebreaking issues in the first office ui fabric relase which made me switch to something else. I think they fixed most of them by now but i currently don't have the time to continue working on this
